// <auto-generated />
using System;
using EmployeeManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$vRojhxZWmUInP1sWdOccr.UP7H7MsJTCEsubFcn9oBeQBH9vpABjC",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$6KV0ibwC2Fywk7FRNlRCDuWMWbj/wmLSQdUl87KkK0cnSUamIAjpq",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.menon@xyz.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Menon",
                            Phone = "9876543210",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Senior Engineer",
                            Email = "arjun.sharma@xyz.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2021, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sharma",
                            Phone = "9876501234",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "meera.iyer@xyz.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Iyer",
                            Phone = "9898989898",
                            Salary = 520000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Marketing Specialist",
                            Email = "rohan.patil@xyz.com",
                            FirstName = "Rohan",
                            JoinDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Patil",
                            Phone = "9812345678",
                            Salary = 600000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "sneha.desai@xyz.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Desai",
                            Phone = "9822334455",
                            Salary = 580000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Executive",
                            Email = "vikram.singh@xyz.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Singh",
                            Phone = "9800011223",
                            Salary = 540000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "UI Developer",
                            Email = "anjali.kulkarni@xyz.com",
                            FirstName = "Anjali",
                            JoinDate = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kulkarni",
                            Phone = "9876123456",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "rahul.verma@xyz.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2020, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Verma",
                            Phone = "9811122233",
                            Salary = 510000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "Talent Partner",
                            Email = "kavya.rao@xyz.com",
                            FirstName = "Kavya",
                            JoinDate = new DateTime(2021, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rao",
                            Phone = "9890011223",
                            Salary = 610000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Finance Manager",
                            Email = "sanjay.nair@xyz.com",
                            FirstName = "Sanjay",
                            JoinDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Nair",
                            Phone = "9800998877",
                            Salary = 880000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "divya.gupta@xyz.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2019, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Gupta",
                            Phone = "9877001122",
                            Salary = 820000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "manish.joshi@xyz.com",
                            FirstName = "Manish",
                            JoinDate = new DateTime(2023, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Joshi",
                            Phone = "9865321470",
                            Salary = 560000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "nidhi.kapoor@xyz.com",
                            FirstName = "Nidhi",
                            JoinDate = new DateTime(2020, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kapoor",
                            Phone = "9844556677",
                            Salary = 720000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "amit.bose@xyz.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Bose",
                            Phone = "9833445566",
                            Salary = 640000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Logistics Coordinator",
                            Email = "shruti.banerjee@xyz.com",
                            FirstName = "Shruti",
                            JoinDate = new DateTime(2021, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Banerjee",
                            Phone = "9822003344",
                            Salary = 500000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
